### ISSUE TITLE
Update plugin for typedoc 0.21.5

### ISSUE THREAD

**Issue by crystalfp** [tomchen/typedoc-plugin-not-exported#3]
Thanks for the useful plugin, but please update it for the latest version of typedoc. With this version it outputs:
```
> npx typedoc --version
Warning: Application.application is deprecated. Plugins are now passed the application
instance when loaded.
    at exports.load (<my project>\node_modules\typedoc-plugin-not-exported\dist\main.js:12:28)
Info: Loaded plugin <my project>\node_modules\typedoc-plugin-not-exported

TypeDoc 0.21.5
Using TypeScript 4.3.5 from <my project>\node_modules\typescript\lib
```
Info: Windows 10, node 16.6.0

**Comment by aspectom** [comment]
The same happens to me in typedoc 0.22.12 node v12.16.1

**Comment by Zamiell** [comment]
Since the author of this plugin doesn't seem to be around, I have forked the plugin and updated it to work with the latest version of TypeDoc with the help of Gerrit.

You can find it on npm:

```
npm install --save-dev @zamiell/typedoc-plugin-not-exported
```

The source code is here: https://github.com/Zamiell/typedoc-plugin-not-exported/tree/publish

**Comment by Megaemce** [comment]
Thank you @Zamiell for your work!

**Comment by crystalfp** [comment]
@Zamiell your plugin works perfectly. Thanks!
