### ISSUE TITLE
is this working for typedoc 0.23.x?

### ISSUE THREAD

**Issue by lslzl3000** [tomchen/typedoc-plugin-not-exported#5]
I can't get it work, `@notExported` is not working, still no class generated

not support 0.23? or something wrong with my config?

**Comment by lslzl3000** [comment]
this repo is not working anymore

Please check https://github.com/Zamiell/typedoc-plugin-not-exported/tree/publish

**Comment by Zamiell** [comment]
Also, I published it on NPM at: `@zamiell/typedoc-plugin-not-exported`
